"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Load .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-do-not-use-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # Broaden for debugging MVP connections

# CSRF Trusted Origins for Render and Vercel
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com', 'https://*.vercel.app']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'signaling',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# --- 🚀 NUCLEAR PRODUCTION DIAGNOSTICS 🚀 ---
import time
VERSION_TAG = f"10MAR_v2_FINAL_{int(time.time())}"
print(f"\n{'='*40}")
print(f"DEBUG: DEPLOYMENT VERSION: {VERSION_TAG}")
print(f"{'='*40}\n")

raw_redis = (os.getenv('REDIS_URL') or 'redis://127.0.0.1:6379').strip()

# 1. Zero-Cleverness Extraction
# If it's a CLI command, just find the parts.
if '-u ' in raw_redis:
    potential_url = raw_redis.split('-u ')[1].split(' ')[0]
else:
    potential_url = raw_redis

# 2. Extract ONLY the host/port/auth part (ignore the protocol entirely)
# We find where '://' is, or where ':' is if no '://'
if '://' in potential_url:
    clean_payload = potential_url.split('://', 1)[1]
elif potential_url.startswith('redis:') or potential_url.startswith('rediss:'):
    clean_payload = potential_url.split(':', 1)[1].lstrip('/')
else:
    clean_payload = potential_url.lstrip('/')

# 3. Explicit Reconstruction
# Logic: If it's Upstash or --tls was requested, use rediss://. Otherwise redis://.
if 'upstash.io' in clean_payload.lower() or '--tls' in raw_redis.lower():
    REDIS_URL = f"rediss://{clean_payload}"
else:
    REDIS_URL = f"redis://{clean_payload}"

# 4. FINAL sanity check (Masking for safety)
masked_url = REDIS_URL.split('@')[-1] if '@' in REDIS_URL else REDIS_URL
print(f"DEBUG: [CHANNEL_LAYER] Final Connection String: {masked_url}\n")

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
        },
    },
}

CORS_ALLOW_ALL_ORIGINS = True


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
