# Generated by Django 5.1.5 on 2026-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0002_project_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing AI...'), ('Failed', 'AI Processing Failed')], default='Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='calllog',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
